### PR TITLE
Koa v2.x refactoring

### LINKED ISSUE #7: Koa 2 support
Would be nice to add a version for Koa 2 with promises! :)

### PR DESCRIPTION
**Pull request by ifraixedes**
This PR brings the minimal refactoring to fulfill with the Koa v2 middleware signature using promises

I've sent this PR to master but following other koa projects, it probably should be merged into a new separate branch named `v2.x` than `master`

It should close #7 

On the other hand, let me know if you prefer to squash the commits before merging it.

### CODE REVIEW

**Comment by ifraixedes** [comment]
Can someone take a look to this PR and provide feedback?

I would like to be able to install the this version through npm and use in something that I'm working.

**Comment by coderhaoxin** [comment]
you can ping @aheckmann :)

**Comment by aheckmann** [comment]
Thanks! Merged into a new [2x branch](https://github.com/koajs/bunyan-logger/tree/2x).

**Comment by ifraixedes** [comment]
Thanks!
Could you publish this version under `@next` tag to be able to installed through npm?

**Comment by aheckmann** [comment]
done. let me know if that works.

**Comment by ifraixedes** [comment]
It works!

Thank you very much.

**Comment by aheckmann** [comment]
thank you!

**Pull request closed without merging**
